apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: sonarqube
  labels:
    app: postgres
    release: {{ .Release.Name }}
data:
  POSTGRESQL_USERNAME: sonar_user
  POSTGRESQL_DATABASE: sonar_db
  POSTGRESQL_PASSWORD: S0N4RQUB3
