apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sonarqube
  labels:
    app: postgres
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres
