apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  namespace: sonarqube
  labels:
    app: sonarqube
    release: {{ .Release.Name }}
data:
  SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar_db"
  SONARQUBE_JDBC_USERNAME: "sonar_user"
  SONARQUBE_JDBC_PASSWORD: "S0N4RQUB3"
  JAVA_OPTS: "-Xmx2048m"
