apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
  namespace: sonarqube
  labels:
    app: sonarqube
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 9000
    name: sonarqube
  selector:
    app: sonarqube
